### ISSUE TITLE
Panic when using other screener than crypto

### ISSUE THREAD

**Issue by chrim5** [dematron/go-tvscanner#1]
Hi, when trying to get analysis information with e.g. `cl.GetAnalysis("US", "NASDAQ", "MSFT", "1d")` I get a panic:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/dematron/go-tvscanner.(*Scanner).PrepareRecommendations(0xc0000fecb0, 0xc0001879d8, 0x6f964b)
        /home/user/projects/go/pkg/mod/github.com/dematron/go-tvscanner@v0.0.0-20210304194119-a1190286f75f/scanner.go:146 +0x6c5
github.com/dematron/go-tvscanner.(*Scanner).GetAnalysis(0xc0000fecb0, 0x6f848f, 0x2, 0x6f91be, 0x6, 0x6f89f9, 0x4, 0x6f842d, 0x2, 0x0, ...)
        /home/user/projects/go/pkg/mod/github.com/dematron/go-tvscanner@v0.0.0-20210304194119-a1190286f75f/scanner.go:253 +0x925
main.tvScan(0x200000003, 0xc000000180)
        /home/user/projects/go/src/github.com/myproject/main.go:29 +0x14e
main.main()
        /home/user/projects/go/src/github.com/myproject/main.go:19 +0x26
exit status 2
```

Am I missing something or does it currently only work with crypto screener?

Cheers

Edit: Also tried  `cl.GetAnalysis("america", "NASDAQ", "TSLA", "1d")` with the same result - panic

**Comment by dematron** [comment]
Hello. Only crypto screener supported for now.
